[//]: # "Created by Jana Hlavinova, Institute for Statistics and Mathematics, WU Vienna"

```{r, echo=FALSE, results="hide"}
## parameters
# a <- sample(2:9, 1)
# b <- sample(seq(2, 4, 0.1), 1)
# c <- sample(seq(0.5, 0.8, 0.01), 1)
# ## solution
# res <- exp(b * c) * (a * c^(a-1) +
#        b * c^a)
n <- 10

#nominal
Lieblingsfarbe <- function(n){
  sample(c("rot (= 1)", "blau (= 2)", 'grün (= 3)', "schwarz (= 4)", "gelb (= 5)") ,n, replace = TRUE)
}

#nominal
Lieblingsfarbe2 <- function(n){
  sample(c("rot", "blau", 'grün', "schwarz", "gelb") ,n, replace = TRUE)
}

#---------------------------------------------------------------------
#Gruppe1
#---------------------------------------------------------------------

#ordinal
Sprachniveau <- function(n){
  sample(c("A1", "A2", "B1", "B2", "C1", "C2") ,n, replace = TRUE)
}


#ordinal
Gewichtsklasse <- function(n){
  sample(c("40 kg bis 60 kg", "60 kg bis 75 kg", "75 kg bis 90 kg", "90 kg bis 100kg", "100 kg bis 120kg") ,n, replace = TRUE)
}

#ordinal
Gewichtsklasse2 <- function(n){
  sample(c("Superschwergewicht", "Schwergewicht", "Mittelgewicht", "Leichtgewicht") ,n, replace = TRUE)
}

#metrisch
Gewicht <- function(n){
  sample(paste0(50:100, " kg") ,n, replace = TRUE)
}


#metrisch
Ankunftszeiten <- function(n){
  sample(apply(expand.grid(0:23, seq(10,55, by = 5)), 1, paste, collapse=":") ,n, replace = TRUE)
}


Datum <- function(n){
  sample(apply(expand.grid(1:30, 1:12,2015:2018), 1, paste, collapse=".") ,n, replace = TRUE)
}

#nominal
Familienstand <- function(n){
  sample(c("verheiratet (=1)", "geschieden (=2)", "verwitwet (=3)", "ledig (=4)") ,n, replace = TRUE)
}



#nominal
Automarke <- function(n){
  sample(c("Ferrari", "Porsche", "Tesla", "VW", "Opel", "Audi", "BMW", "Mercedes", "Kia", "Toyota", "Renault", "Peugeot", "Citroen") ,n, replace = TRUE)
}
#Automarke(n)

#metrisch
Geschwindigkeit <- function(n){
  sample(140:250,n)
}
#Geschwindigkeit(n)

#nominal
Autofarbe <- function(n){
  sample(c("rot", 'grün', "blau", "silber", "grau", "weiß", "schwarz") ,n, replace = TRUE)
}
#Autofarbe(n)

#metrisch
PS <- function(n){
  sample(60:500, n)
}
#PS(n)

#metrisch
Autolaenge <- function(n){
  rnorm(n, 4.5, 0.5)
}
#Autolaenge(n)

#---------------------------------------------------------------------
#Gruppe2 - ordinal
#---------------------------------------------------------------------
#ordinal
Energieeffizienz <- function(n){
  sample(c("A+++", "A++", "A+", "A", "B", "C", "D") ,n, replace = TRUE)
}
#Energieeffizienz(n)

Rating <- function(n){
  sample(c("AAA", "AA", "A", "BBB", "BB", "B", "C", "D"),n, replace = TRUE)
}
#Rating(n)

Rating2 <- function(n){
  sample(paste0(1:30, "\\%") ,n, replace = TRUE)
}

# Rating3 <- function(n){
#   sample(c("sehr zuverlässig"),n, replace = TRUE)
# }

Konfektionsgroesse <- function(n){
  sample(c("S", "M", "L", "XL") ,n, replace = TRUE)
}
#Konfektionsgroesse(n)

Zufriedenheit <- function(n){
  sample(c("sehr zufrieden", "zufrieden", "gar nicht zufrieden") ,n, replace = TRUE)
}
#Zufriedenheit(n)

#TODo
Filmbewertung <- function(n){
  sample(c('überragend', "gut", 'mittelmäßig', "schlecht") ,n, replace = TRUE)
}
#Filmbewertung(n)

#in Prozent
Filmbewertung2 <- function(n){
  runif(n, 0, 100)
}

#ordinal
Schaerfegrad <- function(n){
  sample(c("sehr scharf", "scharf", "mild") ,n, replace = TRUE)
}
#Filmbewertung2(n)
#---------------------------------------------------------------------
#Gruppe4 - Personenbezogen
#---------------------------------------------------------------------
#Intervallskala
Geburtsjahr <- function(n){
  sample(1950:2000,n, replace = TRUE)
}
#Geburtsjahr(n)

#Intervallskala
Alter <- function(n){
  sample(18:100,n, replace = TRUE)
}
#Alter(n)

#nominal
Beruf <- function(n){
  sample(c("Pensionist","Leit.Angestellter", "Angestellter", "Student", "Lehrling", 'Selbständig'),n, replace = TRUE)
}
#Beruf(n)

Geburtsort <- function(n){
  sample(c("Wien","Baden", "Salzburg", "Innsbruck", "Graz", "Linz", "Wien", "Wien", "Wien") ,n, replace = TRUE)
}
#Geburtsort(n)

#nominal
Kennzeichen <- function(n){
  sample(c(paste("W",seq(10001,99999, by = 23),LETTERS),
           paste0(paste("WU",101:999,LETTERS),LETTERS),
           paste0(paste("S",101:999,LETTERS),LETTERS),
           paste0(paste("I",101:999,LETTERS),LETTERS),
           paste0(paste("G",101:999,LETTERS),LETTERS),
           paste0(paste("L",101:999,LETTERS),LETTERS)),n, replace = TRUE)
}
#Kennzeichen(n)

#metrisch
Einkommen <- function(n){
  rnorm(n, mean = 1500, sd = 500)
}
#Einkommen(n)

#Berufserfahrung

# Geschlecht <- function(n){
#   sample(c("f","m"),n, replace = TRUE)
# }
# Geschlecht(n)

#---------------------------------------------------------------------
#Gruppe4 -
#---------------------------------------------------------------------
#Gruppe
#metrisch
Laermpegel1 <- function(n){
  rnorm(n, mean = 50, sd = 10)
}
#Laermpegel1(n)

#ordinal
Laermpegel2 <- function(n){
  sample(c("Sehr laut", "Laut", "Leise", "Sehr leise") ,n, replace = TRUE)
}
#Laermpegel2(n)

# #ordinal
# Statistiknoten1 <- function(n){
#   sample(1:5,n, replace = TRUE)
# }
#Statistiknoten1(n)
#ordinal
Statistiknoten2 <- function(n){
  sample(c("Sehr gut", "Gut", "Befriedigend", 'Genügend', 'Nicht genügend') ,n, replace = TRUE)
}
#Statistiknoten2(n)
#metrisch
Statistiknoten3 <- function(n){
  sample(paste0(c(40:100,80:100), "\\%") ,n, replace = TRUE)
}
#Statistiknoten3(n)
#Leistungsbewertung
#---------------------------------------------------------------------
#Gruppe5 - anspruchsvoller
#---------------------------------------------------------------------
#nominal
PLZ <- function(n){
  sample(c(paste0(1,0,1:9,0),paste0(1,10:23,0)),n, replace = TRUE)
}
#PLZ(n)

BLZ <- function(n){
  sample(c(10000, 11000, 12000, 14000, 14200, 14900, 15000, 16000, 17000, 18400,
18600, 18800, 19100, 19150, 19190, 19200, 19210, 19220, 19240,
19250, 19370, 19530, 19650, 19810, 20111, 20151, 20320, 20404,
20503, 32000, 34000, 38000, 42390, 43000, 44960, 45010, 51000,
52000, 54000, 56000, 57000, 60000), n)
}
#BLZ(n)

#ordinal
#Kleidungsgroesse
Kleidungsgroesse <- function(n){
  sample(seq(80,120, by = 2),n)#, seq(90,106, by = 4)),n)
}
#Kleidungsgroesse(n)

#metrisch
AnzahlZimmer <- function(n){
  sample(1:4,n, replace = TRUE)
}
#AnzahlZimmer(n)


###############################
# neue kat 5
###############################
# % Hotelkategorien (Sterne)
Hotelkategorien <- function(n){
  sample(c("1 Stern", "2 Sterne", "3 Sterne", "4 Sterne", "5 Sterne"), n, replace = TRUE)
}
# % Hotelkategorien (Prozent)
Hotelkategorien2 <- function(n){
  sample(paste0(c(40:100,80:100), "\\%") ,n, replace = TRUE)
}
# % Hotelkategorien (Designhotel, Pension, Hostel, Hotel, Aparthotel, Campingplatz, Bauernhof, Motel, Boutiquehotel, Sporthotel, Ferienwohnung, Stadthotel, Luxushotel)
Hotelkategorien3 <- function(n){
  sample(c("Designhotel", "Pension", "Hostel", "Hotel", "Aparthotel", "Campingplatz", "Bauernhof", "Motel", "Boutiquehotel", "Sporthotel", "Ferienwohnung", "Stadthotel", "Luxushotel"), n)
}
# % Hotelkategorie (Meer, See, Fluss, Gebirge, Wellness, laendliche Region)
Hotelkategorien4 <- function(n){
  sample(c("Meer", "See", "Fluss", "Gebirge", "Wellness", 'ländliche Region'), n, replace = TRUE)
}
# # % Kueche (Hauben)
# Hotelkueche <- function(n){
#   sample(c("keine Haube", "1 Haube", "2 Hauben", "3 Hauben", "4 Hauben"), n, replace = TRUE)
# }
Hotelkueche <- function(n){
  sample(c("italienisch", 'französisch', 'Wiener Küche', "Fischgerichte", "mexikanisch", "indisch", "japanisch", 'thailändisch', "chinesisch", 'Gourmetküche', "griechisch"), n, replace = TRUE)
}
#############################


skalen_df <- cbind("Ankunftszeiten" = Ankunftszeiten(n),
                   "Familienstand" = Familienstand(n),
                   "Lieblingsfarbe" = Lieblingsfarbe(n),
                   "Lieblingsfarbe" = Lieblingsfarbe2(n),
                   "Datumsangabe" = Datum(n),
                   'Hotelküche' = Hotelkueche(n),
                    #---------------------------------------------------------------------
                   "Sprachniveau" = Sprachniveau(n),

                   "Energieeffizienz" = Energieeffizienz(n),
                   'Bonitätsrating' = Rating(n),
                   'Bonitätsrating' = Rating2(n),
                   "Zufriedenheit" = Zufriedenheit(n),
                   "Filmbewertung" = Filmbewertung(n),
                   "Filmbewertung" = paste0(round(Filmbewertung2(n),2), "\\%"),
                   'Schärfegrad' = Schaerfegrad(n),
                   #---------------------------------------------------------------------
                   "Geburtsjahr" = Geburtsjahr(n),
                   "Alter" = paste(Alter(n), "Jahre"),
                   "Beruf" = Beruf(n),
                   "Geburtsort" = Geburtsort(n),
                   "Kennzeichen" = Kennzeichen(n),
                   "Einkommen" = paste(round(Einkommen(n),2), "EUR"),
                   "Automarke" = Automarke(n),
                   "Geschwindigkeit" = paste(Geschwindigkeit(n), "km/h"),
                   "Autofarbe" = Autofarbe(n),
                   'PS (Pferdestärke)' = paste(PS(n), "PS"),
                   'Autolänge' = paste(round(Autolaenge(n),2), "m"),
                   #---------------------------------------------------------------------
                   'Hotelqualität' = Hotelkategorien(n),
                   'Hotelqualität' = Hotelkategorien2(n),
                   "Hotelkategorie" = Hotelkategorien3(n),
                   "Hotelkategorie" = Hotelkategorien4(n),
                   'Hotelkategorie' = Hotelkategorien(n),
                   "Gewicht" = Gewichtsklasse(n),
                   "Gewicht" = Gewichtsklasse2(n),
                   "Gewicht" = Gewicht(n),
                   #---------------------------------------------------------------------
                   'Lärmpegel' = paste(round(Laermpegel1(n),2), "dB"),
                   'Lärmpegel' = Laermpegel2(n),
                   #"Leistungsbeurteilung" = Statistiknoten1(n),
                   "Leistungsbeurteilung" = Statistiknoten2(n),
                   "Leistungsbeurteilung" = Statistiknoten3(n),
                   "Postleitzahl" = PLZ(n),
                   "Bankleitzahl" = BLZ(n),
                   'Kleidungsgröße' = Konfektionsgroesse(n),
                   'Kleidungsgröße' = paste(Kleidungsgroesse(n), "cm"),
                   "Anzahl Zimmer" = AnzahlZimmer(n))

#print(xtable:::xtable(skalen_df[1:n,],  ), type = "latex",  sanitize.text.function = function(x){x})


#skalen_df
# These are the answers: 1=nominal, 2=ordinal, 3=metrisch
sol <- c(3,1,1,1,3, 1,
         2,   2,2,3,2,2,3,2,
         3,3,1,1,1,3,1,3,1,3,3,
         2,3,1,1,2,2,2,3,
         3,2,2,3, 1,1,2,3,3)

# Q1 Nominalskala
# Q2 Ordinalskala
# Q3 Metrisch

questions <- cbind(c(0,1,1), c(1,1,1), c(1,1,1), c(1,1,0), c(1,1,1), c(1,1,1),
                   c(1,1,0),    c(1,1,0), c(1,1,0), c(0,1,1),c(1,1,0), c(1,1,0), c(1,1,1), c(1,1,0),
                   c(1,1,1), c(1,1,1), c(1,1,0), c(1,1,0), c(1,1,0), c(0,1,1), c(1,1,0), c(0,1,1), c(1,1,0), c(0,1,1), c(0,1,1),
                   c(1,1,1), c(0,1,1), c(1,1,0), c(1,1,0),c(1,1,1), c(1,1,1), c(1,1,0), c(0,1,1),
                   c(0,1,1), c(0,1,1), c(1,1,0), c(0,1,1),    c(1,1,1), c(1,1,1), c(1,1,0), c(1,1,1), c(1,1,1))
rownames(questions) <- c("Q1", "Q2", "Q3")

var_names <- c("Ankunftszeiten", "Familienstand", "Lieblingsfarbe", "Lieblingsfarbe", "Datumsangabe", 'Hotelköche',
                   #---------------------------------------------------------------------
                   "Sprachniveau",
                   "Energieffizienz", 'Bonitätsrating', 'Bonitätsrating', "Zufriedenheit", "Filmbewertung", "Filmbewertung", 'Schärfegrad',
                   #---------------------------------------------------------------------
                   "Geburtsjahr", "Alter", "Beruf", "Geburtsort", "Kennzeichen", "Einkommen",
                   "Automarke", "Geschwindigkeit", "Autofarbe", 'PS (Pferdestärke)', 'Autolänge',
                   #---------------------------------------------------------------------
                    'Hotelqualität', 'Hotelqualität', "Hotelkategorie", "Hotelkategorie", "Hotelkategorie", "Gewicht", "Gewicht", "Gewicht",
                   #---------------------------------------------------------------------
                   'Lärmpegel', 'Lärmpegel',  "Leistungsbeurteilung", "Leistungsbeurteilung",

                   "Postleitzahl", "Bankleitzahl", 'Kleidungsgröße', 'Kleidungsgröße', "Anzahl Zimmer")

skalen_df_final <- rbind(skalen_df, sol, questions, var_names)

selection <- c(sample(1:6,1),
              sample(7:14,1),
              sample(15:25,1),
              sample(26:33,1),
              sample(34:42,1))
skalen_df_selection <- skalen_df_final[,selection]
                                   


scales <- c('Nominalskala', 'Ordinalskala', 'metrischen Skala')

question_selection <- sapply(1:ncol(skalen_df_selection), function(i){
  sample(which(skalen_df_selection[c("Q1", "Q2", "Q3"), i] == 1),1)
})

pooling <- sample(1:5, 5)

qpool <- c(
  paste("Die Variable", skalen_df_selection["var_names", pooling[1]], "ist der", scales[question_selection[pooling[1]]],"zuzuordnen."),
  paste("Die Variable", skalen_df_selection["var_names", pooling[2]], "ist der", scales[question_selection[pooling[2]]],"zuzuordnen."),
  paste("Die Variable", skalen_df_selection["var_names", pooling[3]], "ist der", scales[question_selection[pooling[3]]],"zuzuordnen."),
  paste("Die Variable", skalen_df_selection["var_names", pooling[4]], "ist der", scales[question_selection[pooling[4]]],"zuzuordnen."),
  paste("Die Variable", skalen_df_selection["var_names", pooling[5]], "ist der", scales[question_selection[[pooling[5]]]],"zuzuordnen."))

spool <- sapply(1:ncol(skalen_df_selection), function(i){
  question_selection[pooling[i]] ==  skalen_df_selection["sol",pooling[i]]
})
#answer <- paste(as.numeric(spool), collapse="")

solpool <- c(
  paste("Die Variable", skalen_df_selection["var_names", pooling[1]], "ist der", scales[sol[selection[pooling[1]]]],"zuzuordnen."),
  paste("Die Variable", skalen_df_selection["var_names", pooling[2]], "ist der", scales[sol[selection[pooling[2]]]],"zuzuordnen."),
  paste("Die Variable", skalen_df_selection["var_names", pooling[3]], "ist der", scales[sol[selection[pooling[3]]]],"zuzuordnen."),
  paste("Die Variable", skalen_df_selection["var_names", pooling[4]], "ist der", scales[sol[selection[pooling[4]]]],"zuzuordnen."),
  paste("Die Variable", skalen_df_selection["var_names", pooling[5]], "ist der", scales[sol[selection[pooling[5]]]],"zuzuordnen.")
)
```

Question
========
```{r, echo=FALSE, results='asis'}
#library(xtable)
tab <- skalen_df_selection[1:n, pooling]
rownames(tab) <- 1:n
print(knitr::kable(tab, align = "rccccc"))
```
Die Tabelle oben zeigt die ersten $`r n`$ Untersuchungseinheiten einer Datenmatrix mit 5 verschiedenen Merkmalen. Welche der folgenden Aussagen sind richtig?
$$aaaa$$

Answerlist
----------
* `r qpool[1]`
* `r qpool[2]`
* `r qpool[3]`
* `r qpool[4]`
* `r qpool[5]`

Solution
========


Meta-information
================
exname: First Question
extype: mchoice
exsolution: `r mchoice2string(spool)`
exshuffle: TRUE
