```{r, echo=FALSE, results="hide"}
## parameters
# a <- sample(2:9, 1)
# b <- sample(seq(2, 4, 0.1), 1)
# c <- sample(seq(0.5, 0.8, 0.01), 1)
# ## solution
# res <- exp(b * c) * (a * c^(a-1) +
#        b * c^a)
numberOfQuestions <- 5L
questions <- c(
'Die Bankleitzahl ist eine metrische Variable.',
'Die Bankleitzahl ist eine kategoriale Variable.',
'Die Bankleitzahl wird auf einer Intervallskala gemessen.',
'Die Bankleitzahl wird auf einer Quotientenskala gemessen.',
'Die Bankleitzahl wird auf einer Ordinalskala gemessen.',
'Die Bankleitzahl wird auf einer Nominalskala gemessen.',
'Die Kredithöhe ist eine metrische Variable.',
'Die Kredithöhe  ist eine kategoriale Variable.',
'Die Kredithöhe wird auf einer Intervallskala gemessen.',
'Die Kredithöhe wird auf einer Quotientenskala gemessen.',
'Die Kredithöhe wird auf einer Ordinalskala gemessen.',
'Die Kredithöhe wird auf einer Nominalskala gemessen.',
'Das Rating ist eine metrische Variable.',
'Das Rating ist eine kategoriale Variable.',
'Das Rating wird auf einer Intervallskala gemessen.',
'Das Rating wird auf einer Quotientenskala gemessen.',
'Das Rating wird auf einer Ordinalskala gemessen.',
'Das Rating wird auf einer Nominalskala gemessen.',
'Die Rechtsform ist eine metrische Variable.', 
'Die Rechtsform ist eine kategoriale Variable.',
'Die Rechtsform wird auf einer Intervallskala gemessen.',
'Die Rechtsform wird auf einer Quotientenskala gemessen.',
'Die Rechtsform wird auf einer Ordinalskala gemessen.',
'Die Rechtsform wird auf einer Nominalskala gemessen.',
'Die Klassifikation des Wirtschaftszweiges ist eine metrische Variable.', 
'Die Klassifikation des Wirtschaftszweiges ist eine kategoriale Variable.',
'Die Klassifikation des Wirtschaftszweiges wird auf einer Intervallskala gemessen.',
'Die Klassifikation des Wirtschaftszweiges wird auf einer Quotientenskala gemessen.',
'Die Klassifikation des Wirtschaftszweiges wird auf einer Ordinalskala gemessen.',
'Die Klassifikation des Wirtschaftszweiges wird auf einer Nominalskala gemessen.',
'Der Boxplot ist geeignet um Kredithöhen zu visualisieren.', 
'Der Boxplot ist geeignet um die Bankleitzahlen der Kreditgeber zu visualisieren.', 
'Der Mittelwert der Klassifikation des Wirtschaftszweiges widerspiegelt die durchschnittliche Wirtschaftszweigeinteilung des Kreditportfolios.',
'Der Modus der Klassifikation des Wirtschaftszweiges gibt den Wirtschaftszweig mit den meisten Kreditnehmern im Portfolio an.',
'Der Median ist eine geeignete robuste Methode um die Lage der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Der Mittelwert ist eine geeignete robuste Methode um die Lage der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Der Median ist eine geeignete robuste Methode um die Streuung der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Der Mittelwert ist eine geeignete robuste Methode um die Streuung der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Die Interquartilsdistanz ist eine geeignete robuste Methode um die Lage der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Die Standardabweichung ist eine geeignete robuste Methode um die Lage der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Die Varianz ist eine geeignete robuste Methode um die Lage der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Die Interquartilsdistanz ist eine geeignete robuste Methode um die Streuung der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Die Standardabweichung ist eine geeignete robuste Methode um die Streuung der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.',
'Die Varianz ist eine geeignete robuste Methode um die Streuung der Kredithöhe des gesamten gemeldeten Kreditportfolios über mehrere Monate zu vergleichen.')
answers <- as.logical(c(0,1,0,0,0,1,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,1,1,0,0,1,1,0,0,0,0,0,0,1,0,0))
deactivated <- c(3, 4, 9, 10, 15, 16, 21, 22, 27, 28) ## easy to see from the line numbers
if (FALSE) { ## check
	questions[deactivated]
}
questions <- questions[-deactivated]
answers <- answers[-deactivated]

if (numberOfQuestions == 'firsthalf') {
 chosen <- 1:floor(length(questions)/2)
} else if (numberOfQuestions == 'secondhalf') {
 chosen <- ceiling(length(questions)/2 + .1):length(questions)
} else {
 chosen <- sample(seq(along=questions), numberOfQuestions)
}

q1 <- questions[chosen[1]]
q2 <- questions[chosen[2]]
q3 <- questions[chosen[3]]
q4 <- questions[chosen[4]]
q5 <- questions[chosen[5]]
a1 <- answers[chosen[1]]
a2 <- answers[chosen[2]]
a3 <- answers[chosen[3]]
a4 <- answers[chosen[4]]
a5 <- answers[chosen[5]]
q <- questions[chosen]
a <- answers[chosen]
answer <- as.numeric(answers[chosen])
#answer <- paste(as.numeric(answer), collapse="")
```

Question
========
Die österreichischen Banken sind verpflichtet Ihre größten Kreditnehmer (Kredithöhe $> 350.000$ EUR) in das zentrale Kreditregister der Österreichischen Nationalbank zu melden. In der monatlichen Meldung werden folgende Variablen erhoben: 

* Name des Kreditnehmers
* Bankleitzahl des Kreditgebers/der Bank
* Kredithöhe
* Rating: Bonitätsbeurteilung des Kreditnehmers auf einer vordefinierten Ratingskala (AAA, AA, A, BBB, B, C, D)
* Rechtsform des Kreditnehmers (z.B. natürliche Person, GmbH, AG, etc.)
* Klassifikation des Wirtschaftszweiges (z.B. 41.00, steht für den Sektor Baugewerbe)

Welche der folgenden Aussagen sind richtig?

Answerlist
----------
* `r q1`
* `r q2`
* `r q3`
* `r q4`
* `r q5`


Solution
========

Meta-information
================
exname: First Question
extype: mchoice
exsolution: `r mchoice2string(a)`
exshuffle: TRUE
